[2023-04-10 23:08:25,194] INFO _log() L224  127.0.0.1 - - [10/Apr/2023 23:08:25] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-10 23:08:45,284] INFO _log() L224  127.0.0.1 - - [10/Apr/2023 23:08:45] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-10 23:09:40,218] INFO _log() L224  127.0.0.1 - - [10/Apr/2023 23:09:40] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-10 23:11:35,764] INFO _log() L224  127.0.0.1 - - [10/Apr/2023 23:11:35] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-10 23:11:41,626] WARNING add_cliente() L189  Erro ao adicionar cliente 'teste1', Cliente de mesmo nome já salvo na base :/ - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\app.py L189 
[2023-04-10 23:11:41,627] INFO _log() L224  127.0.0.1 - - [10/Apr/2023 23:11:41] "[31m[1mPOST /cliente HTTP/1.1[0m" 409 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-10 23:15:06,216] INFO _log() L224  127.0.0.1 - - [10/Apr/2023 23:15:06] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-10 23:15:12,197] WARNING add_cliente() L189  Erro ao adicionar cliente 'teste1', Cliente de mesmo nome já salvo na base :/ - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\app.py L189 
[2023-04-10 23:15:12,198] INFO _log() L224  127.0.0.1 - - [10/Apr/2023 23:15:12] "[31m[1mPOST /cliente HTTP/1.1[0m" 409 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-10 23:16:12,950] INFO _log() L224  127.0.0.1 - - [10/Apr/2023 23:16:12] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-10 23:16:15,512] WARNING add_cliente() L189  Erro ao adicionar cliente 'teste1', Cliente de mesmo nome já salvo na base :/ - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\app.py L189 
[2023-04-10 23:16:15,513] INFO _log() L224  127.0.0.1 - - [10/Apr/2023 23:16:15] "[31m[1mPOST /cliente HTTP/1.1[0m" 409 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-10 23:16:49,608] INFO _log() L224  127.0.0.1 - - [10/Apr/2023 23:16:49] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-10 23:16:57,556] WARNING add_cliente() L189  Erro ao adicionar cliente 'teste1', Cliente de mesmo nome já salvo na base :/ - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\app.py L189 
[2023-04-10 23:16:57,557] INFO _log() L224  127.0.0.1 - - [10/Apr/2023 23:16:57] "[31m[1mPOST /cliente HTTP/1.1[0m" 409 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-10 23:17:30,015] INFO _log() L224  127.0.0.1 - - [10/Apr/2023 23:17:30] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-10 23:17:36,378] WARNING add_cliente() L189  Erro ao adicionar cliente 'teste1', Cliente de mesmo nome já salvo na base :/ - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\app.py L189 
[2023-04-10 23:17:36,378] INFO _log() L224  127.0.0.1 - - [10/Apr/2023 23:17:36] "[31m[1mPOST /cliente HTTP/1.1[0m" 409 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-10 23:19:15,509] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.15.138:5000 (Press CTRL+C to quit) - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-10 23:19:36,531] WARNING add_cliente() L189  Erro ao adicionar cliente 'teste1', Cliente de mesmo nome já salvo na base :/ - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\app.py L189 
[2023-04-10 23:19:36,533] INFO _log() L224  127.0.0.1 - - [10/Apr/2023 23:19:36] "[31m[1mPOST /cliente HTTP/1.1[0m" 409 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-10 23:19:43,666] INFO _log() L224  127.0.0.1 - - [10/Apr/2023 23:19:43] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-10 23:19:51,127] WARNING add_cliente() L189  Erro ao adicionar cliente 'teste1', Cliente de mesmo nome já salvo na base :/ - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\app.py L189 
[2023-04-10 23:19:51,128] INFO _log() L224  127.0.0.1 - - [10/Apr/2023 23:19:51] "[31m[1mPOST /cliente HTTP/1.1[0m" 409 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-10 23:21:07,646] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.15.138:5000 (Press CTRL+C to quit) - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-10 23:21:17,942] WARNING add_cliente() L189  Erro ao adicionar cliente 'teste1', Cliente de mesmo nome já salvo na base :/ - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\app.py L189 
[2023-04-10 23:21:17,943] INFO _log() L224  127.0.0.1 - - [10/Apr/2023 23:21:17] "[31m[1mPOST /cliente HTTP/1.1[0m" 400 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-10 23:22:40,551] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.15.138:5000 (Press CTRL+C to quit) - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-10 23:22:45,225] INFO _log() L224  127.0.0.1 - - [10/Apr/2023 23:22:45] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-10 23:22:51,262] WARNING add_cliente() L189  Erro ao adicionar cliente 'teste1', Cliente de mesmo nome já salvo na base :/ - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\app.py L189 
[2023-04-10 23:22:51,263] INFO _log() L224  127.0.0.1 - - [10/Apr/2023 23:22:51] "[31m[1mPOST /cliente HTTP/1.1[0m" 409 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-10 23:23:17,162] WARNING add_cliente() L189  Erro ao adicionar cliente 'teste1', Cliente de mesmo nome já salvo na base :/ - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\app.py L189 
[2023-04-10 23:23:17,163] INFO _log() L224  127.0.0.1 - - [10/Apr/2023 23:23:17] "[31m[1mPOST /cliente HTTP/1.1[0m" 409 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-10 23:23:54,805] INFO _log() L224  127.0.0.1 - - [10/Apr/2023 23:23:54] "POST /cliente HTTP/1.1" 200 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-10 23:24:25,146] INFO _log() L224  127.0.0.1 - - [10/Apr/2023 23:24:25] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-10 23:24:27,937] INFO _log() L224  127.0.0.1 - - [10/Apr/2023 23:24:27] "OPTIONS /cliente HTTP/1.1" 200 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-10 23:24:27,953] INFO _log() L224  127.0.0.1 - - [10/Apr/2023 23:24:27] "[35m[1mDELETE /cliente HTTP/1.1[0m" 204 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-10 23:24:32,142] INFO _log() L224  127.0.0.1 - - [10/Apr/2023 23:24:32] "POST /cliente HTTP/1.1" 200 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 18:09:51,299] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.15.138:5000 (Press CTRL+C to quit) - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-11 18:10:23,395] INFO _log() L224  127.0.0.1 - - [11/Apr/2023 18:10:23] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
